error_log /tmp/novnc-nginx-error.log info;
pid /tmp/novnc-nginx.pid;

events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log /tmp/novnc-nginx-access.log;

  client_body_temp_path /tmp/novnc-nginx-client-body;
  proxy_temp_path       /tmp/novnc-nginx-proxy;
  fastcgi_temp_path     /tmp/novnc-nginx-fastcgi;
  uwsgi_temp_path       /tmp/novnc-nginx-uwsgi;
  scgi_temp_path        /tmp/novnc-nginx-scgi;

  server {
    listen 6081;
    listen [::]:6081;

    location / {
      root /tmp/novnc-coder;
      index index.html;
    }

    location = /vnc.html {
      alias /usr/share/novnc/vnc.html;
    }

    location = /vnc_lite.html {
      alias /usr/share/novnc/vnc_lite.html;
    }

    location = /vnc_auto.html {
      alias /usr/share/novnc/vnc_auto.html;
    }

    location /app/ {
      alias /usr/share/novnc/app/;
    }

    location /core/ {
      alias /usr/share/novnc/core/;
    }

    location /vendor/ {
      alias /usr/share/novnc/vendor/;
    }

    location /include/ {
      alias /usr/share/novnc/include/;
    }

    location /utils/ {
      alias /usr/share/novnc/utils/;
    }

    location /websockify {
      proxy_pass http://127.0.0.1:6080/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 86400;
    }
  }
}
